# Generated by Django 6.0 on 2025-12-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addess',
            new_name='address',
        ),
    ]
